// 60 days of SAMPLE club life, generated by calling the real services with the injected clock (§11.2).
// No online payments are simulated (there is no live gateway): portal bookings are paid at the desk, shop orders
// are pay-at-pickup or pay-on-delivery, and every UPI/card payment carries its proof. Staff open a cash drawer each
// morning and close it at night with a count.
// Nothing here writes ledger, stock or booking rows directly — every row comes from a service call, so every
// §9 invariant holds by construction. Rule rejections during the simulation (a slot already taken, a member at
// their daily limit…) are expected and counted; any other error stops the seed.
import { clock } from "@/lib/clock";
import { addDays, addMonths, ageOn, istDate, istToUtc, minutesToTime, timeToMinutes } from "@/lib/time";
import { prisma } from "@/server/db";
import { DomainError } from "@/server/errors";
import { PUBLIC, type UserActor } from "@/server/rbac/actor";
import { runDailyJobs, runFrequentJobs } from "@/server/jobs";
import { cancelBooking, createBooking } from "@/server/services/booking";
import { createSocialSession, joinSession } from "@/server/services/social";
import { checkIn } from "@/server/services/checkin";
import { createMember, renewMembership, upgradeMembership } from "@/server/services/membership";
import { recordCounterPayment } from "@/server/services/payments";
import { closeDrawer, currentDrawer, myDrawer, openDrawer } from "@/server/services/drawers";
import { counterSale, checkout, setOrderStatus, setTicketStatus, cancelOrder } from "@/server/services/shop";
import { receiveStock } from "@/server/services/inventory";
import { addLines, carryTab, closeBarDay, closeTab, openTab, sendToKitchen, setLineStatus, settleTab, verifyGuestId, voidLine } from "@/server/services/bar";
import { clockIn, clockOut, assignShift, requestLeave, decideLeave } from "@/server/services/staff";
import { createExpense, payExpense } from "@/server/services/expenses";
import { approvePayrollRun, createPayrollRun, payPayrollRun } from "@/server/services/payroll";
import { createClient, createDraft, issueInvoice } from "@/server/services/invoices";
import { createEnquiry, createLead, createQuote, createTrialBooking, logActivity, markLost, markInterested } from "@/server/services/crm";
import { createMaintenance } from "@/server/services/booking";
import { SAMPLE_PINCODES, seedPasswords, type Staff } from "./base";
import { tender, type CounterMethod } from "./proof";

// ───────── deterministic randomness ─────────
let seedState = 20261012;
function rand(): number {
  seedState |= 0;
  seedState = (seedState + 0x6d2b79f5) | 0;
  let t = Math.imul(seedState ^ (seedState >>> 15), 1 | seedState);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}
const pick = <T,>(xs: T[]): T => xs[Math.floor(rand() * xs.length)];
const chance = (p: number) => rand() < p;
const between = (a: number, b: number) => a + Math.floor(rand() * (b - a + 1));

const FIRST = ["Aditya", "Priya", "Rohan", "Ananya", "Vikram", "Sneha", "Arjun", "Kavya", "Ishaan", "Meera", "Kabir", "Diya", "Reyansh", "Saanvi", "Aryan", "Tara", "Vivaan", "Anika", "Dhruv", "Pooja", "Nikhil", "Ritu", "Siddharth", "Nisha", "Karan", "Aisha", "Manav", "Zara", "Yash", "Lavanya", "Harsh", "Riya", "Om", "Simran", "Parth", "Bhavna", "Jay", "Tanvi", "Neil", "Esha"];
const LAST = ["Patel", "Shah", "Mehta", "Desai", "Joshi", "Iyer", "Nair", "Reddy", "Kapoor", "Malhotra", "Gupta", "Verma", "Bose", "Das", "Khan", "Fernandes", "Rao", "Pillai", "Trivedi", "Bhatt"];
const name = () => `${pick(FIRST)} ${pick(LAST)}`;

export type SeedStats = Record<string, number>;
const stats: SeedStats = {};
const bump = (k: string, n = 1) => (stats[k] = (stats[k] ?? 0) + n);

/** Run a simulated attempt. Expected business-rule rejections are counted; anything else aborts the seed. */
async function attempt<T>(label: string, fn: () => Promise<T>): Promise<T | null> {
  try {
    const r = await fn();
    bump(`${label}.ok`);
    return r;
  } catch (e) {
    if (e instanceof DomainError && e.code !== "VALIDATION_FAILED" && e.code !== "FORBIDDEN" && e.code !== "NOT_FOUND") {
      bump(`${label}.rejected.${e.code}`);
      return null;
    }
    console.error(`Seed step "${label}" failed unexpectedly at ${clock.now().toISOString()}`);
    throw e;
  }
}

const at = (day: string, time: string) => clock.set(istToUtc(day, time));

/** A day's events run in time order, so the injected clock only moves forward. Events may schedule follow-ups. */
class DayQueue {
  private items: Array<{ t: number; seq: number; fn: () => Promise<unknown> }> = [];
  private seq = 0;
  constructor(private readonly day: string) {}
  add(time: string | number, fn: () => Promise<unknown>) {
    const t = typeof time === "number" ? time : timeToMinutes(time);
    this.items.push({ t: Math.min(t, 24 * 60 - 1), seq: this.seq++, fn });
  }
  async run() {
    let last = -1;
    while (this.items.length) {
      this.items.sort((a, b) => a.t - b.t || a.seq - b.seq);
      const next = this.items.shift()!;
      const t = Math.max(next.t, last);
      last = t;
      clock.set(istToUtc(this.day, minutesToTime(t)));
      await next.fn();
    }
  }
}

type Ctx = {
  staff: Staff;
  today: string;
  first: string;
  personas: Record<string, string>;
  members: string[]; // member ids with a password (portal users)
  juniors: Set<string>;
  courts: Array<{ id: string; name: string; sport: string }>;
  variants: Array<{ id: string; sku: string; price: number; trackStock: boolean; isRestring: boolean }>;
  menu: Array<{ id: string; isAlcoholic: boolean; category: string }>;
  tables: Array<{ id: string; number: number }>;
};

let phoneSeq = 9_700_000_000;
const nextPhone = () => String(++phoneSeq);

const MEMBER_PASSWORD = () => seedPasswords().member;
const anyMethod = (...ms: CounterMethod[]) => tender(pick(ms));

// ───────── cash drawers (8.4) ─────────

const DRAWERS: Array<[key: string, area: "DESK" | "SHOP" | "BAR" | "OFFICE", float: number]> = [
  ["desk", "DESK", 200000], ["desk2", "DESK", 100000], ["shop", "SHOP", 100000], ["bar", "BAR", 200000], ["bar2", "BAR", 0], ["accounts", "OFFICE", 0], ["manager", "OFFICE", 0],
];

export async function openDrawers(staff: Staff) {
  for (const [key, area, float] of DRAWERS) {
    if (!(await currentDrawer(prisma, staff[key]))) await openDrawer(staff[key], { area, openingFloat: float });
  }
}

/** Night close: counted = expected, with an occasional small variance so the reconciliation has something to show. */
export async function closeDrawers(staff: Staff, allowVariance = true) {
  for (const [key] of DRAWERS) {
    const d = await myDrawer(staff[key]);
    if (!d.open) continue;
    const variance = allowVariance && (key === "bar" || key === "desk") && chance(0.08) ? pick([-5000, -2000, 1000]) : 0;
    await closeDrawer(staff[key], { cashCounted: Math.max(0, d.open.cashExpected + variance), note: variance ? "counted twice" : undefined });
  }
}

// ───────── members ─────────

/** A member whose plan starts on the current clock day. `kind` shapes the history the judges will look for. */
async function signUp(ctx: Ctx, opts: { plan: "GOLD" | "SILVER" | "JUNIOR"; months: 1 | 3 | 12; junior?: boolean; turning18InDays?: number; email?: boolean }) {
  const today = istDate(clock.now());
  let dob: string;
  if (opts.turning18InDays !== undefined) dob = addDays(addMonths(ctx.today, -12 * 18), opts.turning18InDays);
  else if (opts.junior) dob = addDays(addMonths(today, -12 * between(10, 16)), -between(0, 300));
  else dob = addDays(addMonths(today, -12 * between(19, 58)), -between(0, 300));
  const nm = name();
  const r = await attempt("member.signup", () =>
    createMember(ctx.staff[pick(["desk", "desk2"])], {
      name: nm, phone: nextPhone(), email: opts.email === false ? undefined : `${nm.toLowerCase().replace(/[^a-z]/g, ".")}.${phoneSeq}@example.com`, dob,
      password: MEMBER_PASSWORD(), emergencyContactName: "Family", emergencyContactPhone: "9820000000",
      ...(ageOn(dob, today) < 18 ? { guardianName: `${nm.split(" ")[1]} (parent)`, guardianPhone: String(9_600_000_000 + phoneSeq - 9_700_000_000) } : {}),
      plan: { code: opts.plan, months: opts.months, payment: anyMethod("UPI", "UPI", "CARD", "CASH") },
    }),
  );
  if (r) {
    ctx.members.push(r.memberId);
    if (opts.plan === "JUNIOR") ctx.juniors.add(r.memberId);
  }
  return r;
}

// ───────── bookings ─────────

const SLOT_TIMES = ["06:00", "07:00", "07:30", "08:00", "09:00", "10:00", "11:30", "16:00", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00"];

const actorCache = new Map<string, UserActor>();
async function memberActor(p: { memberId: string }): Promise<UserActor> {
  const hit = actorCache.get(p.memberId);
  if (hit) return hit;
  const m = await prisma.member.findUniqueOrThrow({ where: { id: p.memberId } });
  const a: UserActor = { kind: "USER", userId: m.userId!, role: "MEMBER", name: m.name, memberId: m.id, employeeId: null };
  actorCache.set(p.memberId, a);
  return a;
}

async function makeBookingsFor(ctx: Ctx, day: string, count: number, opts: { avoidCourt1Evening?: boolean; excludePersonas?: boolean } = {}) {
  const pool = opts.excludePersonas ? ctx.members.filter((m) => !Object.values(ctx.personas).includes(m)) : ctx.members;
  for (let i = 0; i < count; i++) {
    const court = pick(ctx.courts);
    const time = pick(SLOT_TIMES);
    if (opts.avoidCourt1Evening && court.name === "Court 1" && timeToMinutes(time) >= timeToMinutes("17:00")) continue;
    const players: Array<{ memberId: string } | { guest: { name: string } }> = [];
    const primaryMember = chance(0.8);
    players.push(primaryMember ? { memberId: pick(pool) } : { guest: { name: name() } });
    const extra = between(0, court.sport === "CRICKET" ? 3 : 2);
    for (let k = 0; k < extra; k++) players.push(chance(0.6) ? { memberId: pick(pool) } : { guest: { name: name() } });
    const channel = primaryMember && chance(0.45) ? "ONLINE_MEMBER" : pick(["FRONT_DESK", "PHONE", "MESSAGE", "WALK_IN"] as const);
    const actor = channel === "ONLINE_MEMBER" ? await memberActor(players[0] as { memberId: string }) : ctx.staff[pick(["desk", "desk2"])];
    // Portal bookings are paid at the desk (no online gateway in the sample club).
    const payment = channel !== "ONLINE_MEMBER" && chance(0.5) ? ({ kind: "COUNTER", ...anyMethod("CASH", "UPI", "CARD") } as const) : ({ kind: "LATER" } as const);
    await attempt("booking.create", () => createBooking(actor, { courtId: court.id, date: day, startTime: time, players, channel, payment, primaryIndex: 0 }));
  }
}

/** Morning: a few cancellations (late ones get no refund). Then at session time: dues are collected and players check in. */
async function planSessions(ctx: Ctx, q: DayQueue, day: string) {
  const [from, to] = [istToUtc(day), istToUtc(addDays(day, 1))];
  const bookings = await prisma.booking.findMany({
    where: { status: "CONFIRMED", reservation: { startAt: { gte: from, lt: to } } },
    include: { reservation: true, players: true },
  });
  for (const b of bookings) {
    const startMin = Math.round((b.reservation.startAt.getTime() - from.getTime()) / 60_000);
    if (chance(0.07)) {
      q.add("05:45", () => attempt("booking.cancel", () => cancelBooking(ctx.staff.desk, b.id, chance(0.5) ? { refundMethod: "CASH", reason: "plans changed" } : { refundMethod: "UPI", refundReference: tender("UPI").reference, reason: "plans changed" })));
      continue;
    }
    if (chance(0.12)) continue; // no-show: the job marks it at the end of the day
    q.add(Math.max(0, startMin - 10), async () => {
      const bill = b.billId ? await prisma.bill.findUniqueOrThrow({ where: { id: b.billId } }) : null;
      const due = bill && !bill.closedAt ? bill.total - (bill.amountPaid - bill.amountRefunded) : 0;
      if (bill && due > 0) await attempt("booking.pay_desk", () => recordCounterPayment(ctx.staff.desk, { billId: bill.id, amount: due, ...anyMethod("CASH", "UPI", "CARD") }));
      for (const p of b.players.filter((x) => !x.removedAt)) {
        if (chance(0.9)) await attempt("checkin", () => checkIn(ctx.staff.desk, { bookingPlayerId: p.id }));
      }
    });
  }
}

// ───────── shop ─────────

function planShop(ctx: Ctx, q: DayQueue) {
  const sellable = ctx.variants.filter((v) => v.sku !== "RKT-PS97" && !v.isRestring && v.trackStock);
  for (let i = 0, n = between(2, 6); i < n; i++) {
    q.add(between(9 * 60, 20 * 60), async () => {
      const items = Array.from({ length: between(1, 2) }, () => ({ variantId: pick(sellable).id, qty: chance(0.8) ? 1 : 2 }));
      const member = chance(0.6) ? pick(ctx.members) : undefined;
      await attempt("shop.counter_sale", () => counterSale(ctx.staff[pick(["shop", "desk"])], { memberId: member, items, payments: [anyMethod("CASH", "UPI", "CARD")] }));
    });
  }
  if (chance(0.3)) {
    q.add("10:30", async () => {
      const restring = ctx.variants.find((v) => v.isRestring)!;
      const r = await attempt("shop.restring", () =>
        counterSale(ctx.staff.shop, { memberId: pick(ctx.members), items: [{ variantId: restring.id, qty: 1 }], payments: [tender("UPI")], restring: { racket: pick(["Babolat Pure Drive", "Wilson Blade 98", "Head Speed MP", "Yonex Ezone"]), notes: `${between(22, 26)} kg` } }),
      );
      if (!r) return;
      const t = await prisma.serviceTicket.findFirstOrThrow({ where: { code: r.tickets[0] } });
      q.add("15:00", () => attempt("ticket.progress", () => setTicketStatus(ctx.staff.shop, t.id, "IN_PROGRESS")));
      q.add("18:00", () => attempt("ticket.ready", () => setTicketStatus(ctx.staff.shop, t.id, "READY")));
      if (chance(0.8)) q.add("20:00", () => attempt("ticket.collected", () => setTicketStatus(ctx.staff.shop, t.id, "COLLECTED")));
    });
  }
  for (let i = 0, n = between(0, 2); i < n; i++) {
    const placedAt = between(8 * 60, 17 * 60);
    q.add(placedAt, async () => {
      const item = pick(sellable);
      const asMember = chance(0.7);
      const delivery = chance(0.35);
      const actor = asMember ? await memberActor({ memberId: pick(ctx.members) }) : PUBLIC;
      const pincode = pick(SAMPLE_PINCODES);
      const o = await attempt("shop.checkout", () =>
        checkout(actor, {
          items: [{ variantId: item.id, qty: 1 }], fulfilment: delivery ? "DELIVERY" : "PICKUP",
          address: delivery ? `${between(1, 99)} ${pick(["SG Highway", "CG Road", "Prahlad Nagar", "Bodakdev"])}, Ahmedabad ${pincode}` : undefined,
          pincode: delivery ? pincode : undefined,
          paymentOption: delivery ? "PAY_ON_DELIVERY" : "PAY_AT_PICKUP",
          guest: asMember ? undefined : { name: name(), phone: nextPhone(), email: `visitor${phoneSeq}@example.com` },
        }),
      );
      if (!o) return;
      if (!delivery && chance(0.08)) return; // never collected → the 48-hour pickup hold expires (job)
      if (chance(0.1)) {
        q.add(placedAt + 30, () => attempt("shop.cancel_order", () => cancelOrder(ctx.staff.shop, o.orderId, "customer asked to cancel")));
        return;
      }
      if (delivery) {
        q.add(placedAt + 120, () => attempt("order.packed", () => setOrderStatus(ctx.staff.shop, o.orderId, "PACKED")));
        q.add(placedAt + 180, () => attempt("order.out", () => setOrderStatus(ctx.staff.shop, o.orderId, "OUT_FOR_DELIVERY")));
        q.add(placedAt + 300, async () => {
          await attempt("order.pay_on_delivery", () => recordCounterPayment(ctx.staff.shop, { billId: o.billId, amount: o.total, ...anyMethod("CASH", "UPI") }));
          await attempt("order.delivered", () => setOrderStatus(ctx.staff.shop, o.orderId, "DELIVERED"));
        });
      } else {
        q.add(placedAt + 90, () => attempt("order.ready", () => setOrderStatus(ctx.staff.shop, o.orderId, "READY_FOR_PICKUP")));
        q.add(placedAt + 240, async () => {
          await attempt("order.pay_pickup", () => recordCounterPayment(ctx.staff.shop, { billId: o.billId, amount: o.total, ...anyMethod("CASH", "UPI", "CARD") }));
          await attempt("order.collected", () => setOrderStatus(ctx.staff.shop, o.orderId, "COLLECTED"));
        });
      }
    });
  }
}

async function restockIfLow(ctx: Ctx) {
  const low = await prisma.$queryRaw<{ id: string; sku: string; price: number; reorder_level: number }[]>`
    SELECT v.id, v.sku, v.price, v.reorder_level FROM product_variants v JOIN products p ON p.id = v.product_id
     WHERE p.track_stock AND v.on_hand - v.reserved <= v.reorder_level AND v.sku <> 'RKT-PS97'`;
  for (const v of low) {
    // A few items are left low on purpose so the low-stock list and widget have something to show.
    if (["BAL-GLD4", "ACC-WB-BLK", "SHO-CJB-9", "BAL-CRK-WHT"].includes(v.sku)) continue;
    await attempt("stock.receive", () =>
      receiveStock(ctx.staff.shop, { variantId: v.id, qty: Math.max(6, v.reorder_level * 3), unitCost: Math.round(v.price * 0.58), supplier: "Sports Wholesale Ltd", createPayable: chance(0.7), inputGst: Math.round(v.price * 0.06), dueInDays: 30 }),
    );
  }
}

// ───────── bar ─────────

function planBar(ctx: Ctx, q: DayQueue, day: string, busy: boolean) {
  const bina = ctx.staff.bar;
  const kitchen = ctx.staff.kitchen;
  const opened: string[] = [];
  q.add("16:55", () => attempt("bar.clock_in", () => clockIn(bina)));
  q.add("16:50", () => attempt("kitchen.clock_in", () => clockIn(kitchen)));
  for (let i = 0, n = between(busy ? 8 : 4, busy ? 14 : 9); i < n; i++) {
    const t0 = between(17 * 60, 21 * 60);
    q.add(t0, async () => {
      const member = chance(0.65) ? pick(ctx.members) : null;
      const t = await attempt("bar.open_tab", () =>
        openTab(bina, member ? { memberId: member, tableId: chance(0.8) ? pick(ctx.tables).id : null } : { guest: { name: name() }, tableId: chance(0.8) ? pick(ctx.tables).id : null, guestIdVerified: chance(0.7) }),
      );
      if (!t) return;
      opened.push(t.tabId);
      const pool = member && ctx.juniors.has(member) ? ctx.menu.filter((m) => !m.isAlcoholic) : ctx.menu;
      const items = Array.from({ length: between(1, 4) }, () => ({ menuItemId: pick(pool).id, qty: chance(0.8) ? 1 : 2, note: chance(0.15) ? pick(["no onion", "extra spicy", "less ice", "seat 2"]) : undefined }));
      let added = await attempt("bar.add_lines", () => addLines(bina, t.tabId, { items }));
      if (!added) {
        if (!member) {
          await attempt("bar.verify_id", () => verifyGuestId(bina, t.tabId));
          added = await attempt("bar.add_lines_after_id", () => addLines(bina, t.tabId, { items }));
        } else {
          const soft = items.map((x) => ({ ...x, menuItemId: pick(ctx.menu.filter((m) => !m.isAlcoholic)).id }));
          added = await attempt("bar.add_soft_lines", () => addLines(bina, t.tabId, { items: soft }));
        }
      }
      if (!added) return;
      await attempt("bar.send", () => sendToKitchen(bina, t.tabId));
      const lines = await prisma.tabLine.findMany({ where: { tabId: t.tabId, status: "NEW", kitchenTicketId: { not: null } } });
      if (lines.length > 1 && chance(0.08)) await attempt("bar.void", () => voidLine(bina, lines[0].id, ""));
      const prep = t0 + between(3, 8);
      const ready = prep + between(5, 15);
      for (const l of lines) {
        q.add(prep, () => attempt("kds.preparing", () => setLineStatus(kitchen, l.id, "PREPARING")));
        q.add(ready, () => attempt("kds.ready", () => setLineStatus(kitchen, l.id, "READY")));
        q.add(ready + between(1, 5), () => attempt("kds.served", () => setLineStatus(bina, l.id, "SERVED")));
      }
    });
  }
  q.add("22:15", async () => {
    for (const tabId of opened) {
      const tab = await prisma.tab.findUniqueOrThrow({ where: { id: tabId } });
      if (tab.status !== "OPEN") continue;
      const bill = await prisma.bill.findUniqueOrThrow({ where: { id: tab.billId } });
      const due = bill.total - (bill.amountPaid - bill.amountRefunded);
      if (due <= 0) {
        await attempt("bar.close_tab", () => closeTab(bina, tabId));
        continue;
      }
      if (chance(0.04)) {
        await attempt("bar.carry", () => carryTab(ctx.staff.manager, tabId, "regular member — settles next visit"));
        continue;
      }
      const split = due > 30000 && chance(0.3);
      const payments = split
        ? [{ method: "CASH" as const, amount: Math.floor(due / 2), tendered: Math.ceil(due / 2 / 10000) * 10000 }, { ...tender("UPI"), amount: due - Math.floor(due / 2) }]
        : [{ ...anyMethod("CASH", "UPI", "UPI", "CARD"), amount: due }];
      await attempt("bar.settle", () => settleTab(bina, tabId, { payments }));
    }
  });
  q.add("23:30", async () => {
    // The cash itself is counted when the drawers close (23:50).
    await attempt("bar.clock_out", () => clockOut(bina));
    await attempt("kitchen.clock_out", () => clockOut(kitchen));
  });
  q.add("23:45", () => attempt("bar.close_day", () => closeBarDay(ctx.staff.manager, day)));
}

// ───────── CRM ─────────

function planCrm(ctx: Ctx, q: DayQueue, day: string, d: number) {
  for (let i = 0, n = between(0, 2); i < n; i++) {
    q.add(between(8 * 60, 22 * 60), () =>
      attempt("crm.enquiry", () =>
        createEnquiry({ consent: true, name: name(), phone: nextPhone(), email: `lead${phoneSeq}@example.com`, interest: pick(["Gold membership", "Silver membership", "Junior coaching", "Corporate package", "Cricket nets"]), message: pick(["Do you have coaching?", "What are the timings?", "Can my son join?", "Interested in a corporate tie-up", ""]) }),
      ),
    );
  }
  if (chance(0.25)) q.add("12:00", () => attempt("crm.walkin", () => createLead(ctx.staff.desk, { name: name(), phone: nextPhone(), source: pick(["WALK_IN", "PHONE", "REFERRAL"] as const), interest: "Membership" })));
  if (chance(0.3)) {
    q.add("07:00", () =>
      attempt("crm.trial", () => createTrialBooking({ consent: true, name: name(), phone: nextPhone(), email: `trial${phoneSeq}@example.com`, courtId: pick(ctx.courts).id, date: day, startTime: pick(["14:00", "14:30", "15:00", "15:30"]) })),
    );
  }
  if (d >= 56) return; // the last few days stay untouched so some follow-ups are overdue
  q.add("16:30", async () => {
    const open = await prisma.lead.findMany({ where: { status: { in: ["NEW", "CONTACTED", "QUOTED"] }, createdAt: { lt: clock.now() } }, take: 4, orderBy: { createdAt: "asc" } });
    for (const l of open) {
      const r = rand();
      if (l.status === "NEW") {
        await attempt("crm.call", () => logActivity(ctx.staff.desk, l.id, { type: "CALL", note: "Called — explained plans and timings", nextFollowUpAt: new Date(clock.now().getTime() + 2 * 86_400_000).toISOString() }));
      } else if (l.status === "CONTACTED" && r < 0.6) {
        const qt = await attempt("crm.quote", () => createQuote(ctx.staff.desk, l.id, { lines: [{ planCode: pick(["GOLD", "SILVER"] as const), months: pick([3, 12] as const) }], send: l.email ? "EMAIL" : "LINK" }));
        if (qt && chance(0.5)) await attempt("crm.interested", () => markInterested(qt.token));
      } else if (l.status === "QUOTED" && r < 0.45) {
        const m = await attempt("crm.convert", () =>
          createMember(ctx.staff.desk, {
            name: l.name, phone: l.phone ?? nextPhone(), email: l.email ?? undefined, dob: addDays(addMonths(day, -12 * between(20, 45)), -between(0, 200)),
            password: MEMBER_PASSWORD(), leadId: l.id, plan: { code: "SILVER", months: 3, payment: tender("UPI") },
          }),
        );
        if (m) ctx.members.push(m.memberId);
      } else if (r > 0.85) {
        await attempt("crm.lost", () => markLost(ctx.staff.desk, l.id, pick(["Too expensive", "Joined another club", "Moved away", "No response after 3 calls"])));
      }
    }
  });
}

// ───────── main ─────────

export async function seedHistory(staff: Staff, today: string, personas: Record<string, string>) {
  const first = addDays(today, -60);
  const courts = await prisma.court.findMany({ orderBy: { sortOrder: "asc" } });
  const variants = (await prisma.productVariant.findMany({ include: { product: true } })).map((v) => ({ id: v.id, sku: v.sku, price: v.price, trackStock: v.product.trackStock, isRestring: v.product.isRestring }));
  const menu = (await prisma.menuItem.findMany()).map((m) => ({ id: m.id, isAlcoholic: m.isAlcoholic, category: m.category }));
  const tables = await prisma.barTable.findMany();
  const ctx: Ctx = { staff, today, first, personas, members: Object.values(personas), juniors: new Set([personas.aarav]), courts, variants, menu, tables };

  // Members who were with the club before the window (3- and 12-month memberships), Juniors, and one about to turn 18.
  at(addDays(first, -1), "10:00");
  await openDrawers(staff);
  for (let i = 0; i < 45; i++) await signUp(ctx, { plan: pick(["GOLD", "SILVER", "SILVER", "SILVER"] as const), months: pick([3, 12, 12] as const) });
  for (let i = 0; i < 8; i++) await signUp(ctx, { plan: "JUNIOR", months: 12, junior: true });
  await signUp(ctx, { plan: "JUNIOR", months: 3, turning18InDays: 5 });
  at(addDays(first, -1), "20:00");
  await closeDrawers(staff, false);

  // Weekly Friday social series (E-22) across the window plus two weeks ahead; business clients.
  let firstFriday = first;
  while (new Date(`${firstFriday}T00:00:00Z`).getUTCDay() !== 5) firstFriday = addDays(firstFriday, 1);
  const weeks = Math.ceil((60 + 14 - (Date.parse(firstFriday) - Date.parse(first)) / 86_400_000) / 7);
  await attempt("social.series", () => createSocialSession(staff.manager, { title: "Friday Social", courtIds: [courts[2].id, courts[3].id], date: firstFriday, startTime: "19:00", endTime: "22:00", capacityPerCourt: 12, repeatWeeks: weeks }));
  const clients = [
    await createClient(staff.accounts, { name: "Adani Sports Foundation", gstin: "24AAACA1234D1ZK", address: "Shantigram, Ahmedabad", contactName: "Rakesh Shah", contactEmail: "rakesh@asf.example", paymentTermsDays: 15 }),
    await createClient(staff.accounts, { name: "Mumbai Tech Offsite Co", gstin: "27AAPFU0939F1ZV", address: "BKC, Mumbai", contactName: "Sonal Rao", contactEmail: "sonal@mto.example", paymentTermsDays: 30 }),
    await createClient(staff.accounts, { name: "Riverside Corporate Wellness", gstin: "24AABCR5555K1Z7", address: "Ashram Road, Ahmedabad", contactName: "Imran Sheikh", contactEmail: "imran@rcw.example", paymentTermsDays: 15 }),
  ];

  for (let d = 0; d < 60; d++) {
    const day = addDays(first, d);
    const dow = new Date(`${day}T00:00:00Z`).getUTCDay();
    const busy = dow === 0 || dow === 5 || dow === 6;
    const dom = Number(day.slice(8, 10));
    if (d % 10 === 0) console.log(`  … ${day} (${stats["booking.create.ok"] ?? 0} bookings, ${ctx.members.length} members so far)`);
    const q = new DayQueue(day);

    q.add("00:05", () => runDailyJobs());
    q.add("05:00", () => openDrawers(staff));
    q.add("05:20", () => restockIfLow(ctx));
    q.add("05:30", async () => {
      await makeBookingsFor(ctx, day, busy ? 26 : 18);
      if (d < 59) await makeBookingsFor(ctx, addDays(day, 1), 4, { excludePersonas: d >= 58 });
      if (d === 25) await attempt("maintenance", () => createMaintenance(staff.manager, { courtId: courts[1].id, date: addDays(day, 1), startTime: "06:00", endTime: "09:00", note: "net replacement" }));
      await planSessions(ctx, q, day);
    });
    q.add("10:20", async () => {
      for (let i = 0, n = between(0, 2); i < n; i++) {
        const plan = pick(["GOLD", "SILVER", "SILVER", "JUNIOR"] as const);
        await signUp(ctx, { plan, months: d < 35 && chance(0.6) ? 1 : pick([1, 3, 12] as const), junior: plan === "JUNIOR" });
      }
      if (d >= 30 && d <= 35) await signUp(ctx, { plan: "SILVER", months: 1 }); // these expire within the coming week
    });
    if (d % 3 === 0) {
      q.add("11:10", async () => {
        const ending = await prisma.membership.findMany({ where: { status: "ACTIVE", memberId: { notIn: Object.values(personas) }, endDate: { gte: new Date(`${day}T00:00:00Z`), lte: new Date(`${addDays(day, 4)}T00:00:00Z`) } }, take: 3 });
        for (const m of ending) {
          if (!chance(0.55)) continue;
          const r = await attempt("membership.renew", () => renewMembership(staff.desk, { memberId: m.memberId, months: pick([1, 3] as const) }));
          if (r && r.total > 0) await attempt("membership.renew_pay", () => recordCounterPayment(staff.desk, { billId: r.billId, amount: r.total, ...tender("UPI") }));
        }
      });
    }
    if (d === 20) {
      q.add("11:40", async () => {
        const silver = await prisma.membership.findFirst({ where: { status: "ACTIVE", plan: { code: "SILVER" }, memberId: { notIn: Object.values(personas) } } });
        if (!silver) return;
        const up = await attempt("membership.upgrade", () => upgradeMembership(staff.desk, { memberId: silver.memberId, planCode: "GOLD", months: 3 }));
        if (up && up.total > 0) await attempt("membership.upgrade_pay", () => recordCounterPayment(staff.desk, { billId: up.billId, amount: up.total, ...tender("CARD") }));
      });
    }
    if (dow === 5) {
      q.add("12:00", async () => {
        const ses = await prisma.socialSession.findFirst({ where: { date: new Date(`${day}T00:00:00Z`), status: "SCHEDULED" } });
        if (!ses) return;
        for (let i = 0, n = between(8, 16); i < n; i++) {
          await attempt("social.join", () => joinSession(staff.desk, { sessionId: ses.id, player: chance(0.75) ? { memberId: pick(ctx.members) } : { guest: { name: name() } }, payment: { kind: "COUNTER", ...anyMethod("UPI", "CASH") } }));
        }
        q.add("18:50", async () => {
          const ps = await prisma.socialParticipant.findMany({ where: { sessionId: ses.id, status: "JOINED" } });
          for (const p of ps) if (chance(0.85)) await attempt("social.checkin", () => checkIn(staff.desk, { socialParticipantId: p.id }));
        });
      });
    }
    planShop(ctx, q);
    planBar(ctx, q, day, busy);
    planCrm(ctx, q, day, d);

    // Finance: rent on the 1st, electricity on the 5th, occasional maintenance/marketing.
    if (dom === 1) {
      q.add("12:30", async () => {
        const e = await createExpense(staff.accounts, { vendor: "Riverside Estates", category: "RENT", description: `Rent ${day.slice(0, 7)}`, amount: 25000000, inputGst: 3813559, dueInDays: 7 });
        q.add("15:00", () => payExpense(staff.accounts, e.id, { method: "BANK_TRANSFER", reference: `NEFT-RENT-${day.slice(0, 7)}` }));
      });
    }
    if (dom === 5) {
      q.add("12:30", async () => {
        const e = await createExpense(staff.accounts, { vendor: "Torrent Power", category: "UTILITIES", description: "Electricity — floodlights and clubhouse", amount: between(3500000, 5200000), dueInDays: 10 });
        if (d < 45) q.add("16:00", () => payExpense(staff.accounts, e.id, { method: "BANK_TRANSFER" }));
      });
    }
    if (chance(0.08)) {
      q.add("13:00", async () => {
        const e = await createExpense(staff.accounts, { vendor: pick(["Court Care Services", "GreenTurf Maintenance", "Ahmedabad Print Co"]), category: pick(["MAINTENANCE", "MARKETING"] as const), amount: between(500000, 2500000), inputGst: between(50000, 300000), dueInDays: 15 });
        if (chance(0.6)) await payExpense(staff.accounts, e.id, { method: pick(["UPI", "BANK_TRANSFER"] as const) });
      });
    }
    // Business invoices: paid, part-paid, and one left to go overdue.
    if (d === 3 || d === 18 || d === 33) {
      q.add("14:00", async () => {
        const idx = [3, 18, 33].indexOf(d);
        const draft = await createDraft(staff.accounts, { businessClientId: clients[idx].id, lines: [{ kind: "MANUAL", description: `Corporate court package — ${day.slice(0, 7)}`, qty: 1, unitPrice: between(40, 90) * 100_000 }, { kind: "MANUAL", description: "Team social evening", qty: 1, unitPrice: 1_180_000 }] });
        await issueInvoice(staff.accounts, draft.invoice.id);
        if (idx === 0) q.add("17:00", () => recordCounterPayment(staff.accounts, { billId: draft.bill.id, method: "BANK_TRANSFER", amount: draft.bill.total, reference: "NEFT-ASF-0001" }));
        if (idx === 1) q.add("17:00", () => recordCounterPayment(staff.accounts, { billId: draft.bill.id, method: "BANK_TRANSFER", amount: Math.floor(draft.bill.total / 2), reference: "NEFT-MTO-0001" }));
      });
    }
    // Staff: leave and the roster.
    if (d === 10) {
      q.add("09:00", async () => {
        const lr = await attempt("leave.request", () => requestLeave(staff.desk2, { type: "CASUAL", startDate: addDays(day, 5), endDate: addDays(day, 6), reason: "family wedding" }));
        if (lr) await attempt("leave.approve", () => decideLeave(staff.manager, lr.id, "APPROVED"));
        const lr2 = await attempt("leave.request", () => requestLeave(staff.bar2, { type: "UNPAID", startDate: addDays(day, 8), endDate: addDays(day, 9), reason: "exam" }));
        if (lr2) await attempt("leave.approve", () => decideLeave(staff.manager, lr2.id, "APPROVED"));
      });
    }
    if (d === 40) {
      q.add("09:00", async () => {
        const lr = await attempt("leave.request", () => requestLeave(staff.shop, { type: "SICK", startDate: addDays(day, 1), endDate: addDays(day, 1), reason: "fever" }));
        if (lr) await attempt("leave.reject", () => decideLeave(staff.manager, lr.id, "REJECTED", "Stock count that day — please swap"));
      });
    }
    if (d === 45) {
      q.add("09:00", async () => {
        for (let k = 0; k < 22; k++) {
          const date = addDays(day, k);
          for (const [who, area, st, en] of [["desk", "FRONT_DESK", "06:00", "14:00"], ["desk2", "FRONT_DESK", "14:00", "22:00"], ["shop", "SHOP", "09:00", "18:00"], ["bar", "BAR", "16:00", "23:59"], ["bar2", "BAR", "17:00", "23:00"], ["kitchen", "KITCHEN", "16:30", "23:00"]] as const) {
            await attempt("roster.assign", () => assignShift(staff.manager, { employeeId: staff[who].employeeId!, date, startTime: st, endTime: en, area }));
          }
        }
        await attempt("leave.request", () => requestLeave(staff.desk, { type: "CASUAL", startDate: addDays(day, 20), endDate: addDays(day, 20), reason: "personal errand" })); // left pending
      });
    }
    // Payroll for the previous month: created, approved by the owner, paid.
    if (dom === 2 && d > 0) {
      q.add("11:00", async () => {
        const [y, m] = day.split("-").map(Number);
        const prev = m === 1 ? `${y - 1}-12` : `${y}-${String(m - 1).padStart(2, "0")}`;
        const run = await attempt("payroll.create", () => createPayrollRun(staff.accounts, prev));
        if (!run) return;
        await attempt("payroll.approve", () => approvePayrollRun(staff.owner, run.id));
        q.add("15:00", () => attempt("payroll.pay", () => payPayrollRun(staff.accounts, run.id, { method: "BANK_TRANSFER" })));
      });
    }
    q.add("23:50", () => closeDrawers(staff));
    q.add("23:55", () => runFrequentJobs());
    await q.run();
  }

  // Members book ahead for today (Court 1 stays free this evening for the demo).
  at(addDays(today, -1), "23:57");
  await openDrawers(staff);
  await makeBookingsFor(ctx, today, 10, { avoidCourt1Evening: true, excludePersonas: true }); // personas stay free for the demo
  await closeDrawers(staff, false);
  clock.set(null);
  return { stats, members: ctx.members.length };
}

export function seedSummary() {
  return Object.entries(stats).sort(([a], [b]) => a.localeCompare(b));
}
